//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITcompany.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Data
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee_Data()
        {
            this.Employee_Events_Registration = new HashSet<Employee_Events_Registration>();
        }
    
        public int Emp_ID { get; set; }
        public string Emp_Name { get; set; }
        public string Mobile_No { get; set; }
        public string Email_ID { get; set; }
        public string GENDER { get; set; }
        public string Department { get; set; }
        public string Designation { get; set; }
        public string Marital_Status { get; set; }
        public string Address { get; set; }
        public string Job_Location { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Events_Registration> Employee_Events_Registration { get; set; }
    }
}
