//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITcompany.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events_General_Online
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Events_General_Online()
        {
            this.Employee_Events_Registration = new HashSet<Employee_Events_Registration>();
            this.Events_Reg_General_Online = new HashSet<Events_Reg_General_Online>();
        }
    
        public int EventID { get; set; }
        public string EventName { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.TimeSpan> EventTiming { get; set; }
        public string EventCategory { get; set; }
        public string Venue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Events_Registration> Employee_Events_Registration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Events_Reg_General_Online> Events_Reg_General_Online { get; set; }
    }
}
