//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITcompany.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_applications
    {
        public int application_id { get; set; }
        public Nullable<int> job_id { get; set; }
        public string your_name { get; set; }
        public string mobile_no { get; set; }
        public string email { get; set; }
        public string preferred_location { get; set; }
    
        public virtual Career Career { get; set; }
    }
}
