//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITcompany.Controllers
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITCompanyEntities4 : DbContext
    {
        public ITCompanyEntities4()
            : base("name=ITCompanyEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Career> Careers { get; set; }
        public virtual DbSet<Employee_Data> Employee_Data { get; set; }
        public virtual DbSet<Employee_Events_Registration> Employee_Events_Registration { get; set; }
        public virtual DbSet<Events_General_Online> Events_General_Online { get; set; }
        public virtual DbSet<Events_Reg_General_Online> Events_Reg_General_Online { get; set; }
        public virtual DbSet<job_applications> job_applications { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
